/** Generated by @vite-pwa/assets-generator (minimal-2023 preset); committed to /public.
 *  Filenames only (no path prefix) so both the manifest (base '/') and runtime exports
 *  (BASE_URL) can build their own absolute URLs. Reads no Vite env, so this file is
 *  safely importable from BOTH the browser runtime and the Node-side vite.config.ts. */
export const ICON_FILES = {
  pwa64: 'pwa-64x64.png',
  pwa192: 'pwa-192x192.png',
  pwa512: 'pwa-512x512.png',
  maskable512: 'maskable-icon-512x512.png',
  appleTouch180: 'apple-touch-icon-180x180.png',
  faviconIco: 'favicon.ico',
  faviconSvg: 'favicon.svg',
} as const;

export type IconFileKey = keyof typeof ICON_FILES;
